name = "next-farm-website"
pages_build_output_dir = ".vercel/output/static"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "next-farm-db"
database_id = "40679735-3689-413b-823c-08a36509960a"
migrations_dir = "migrations"
